export const GENRES = [
    { label: 'Alternative Rock', value: 'alternative rock' },
    { label: 'Ambient', value: 'ambient' },
    { label: 'Black Metal', value: 'black metal' },
    { label: 'Blues', value: 'blues' },
    { label: 'Blues Rock', value: 'blues rock' },
    { label: 'Bossa Nova', value: 'bossa nova' },
    { label: 'Breakbeat', value: 'breakbeat' },
    { label: 'Chamber Pop', value: 'chamber pop' },
    { label: 'Chillout', value: 'chillout' },
    { label: 'Classical', value: 'classical' },
    { label: 'Classic Rock', value: 'classic rock' },
    { label: 'Contemporary Classical', value: 'contemporary classical' },
    { label: 'Contemporary Jazz', value: 'contemporary jazz' },
    { label: 'Contemporary R&B', value: 'contemporary r&b' },
    { label: 'Country', value: 'country' },
    { label: 'Country Rock', value: 'country rock' },
    { label: 'Dance', value: 'dance' },
    { label: 'Dance-Pop', value: 'dance-pop' },
    { label: 'Dancehall', value: 'dancehall' },
    { label: 'Dark Ambient', value: 'dark ambient' },
    { label: 'Dark Wave', value: 'dark wave' },
    { label: 'Death Metal', value: 'death metal' },
    { label: 'Deep House', value: 'deep house' },
    { label: 'Detroit Techno', value: 'detroit techno' },
    { label: 'Disco', value: 'disco' },
    { label: 'Doom Metal', value: 'doom metal' },
    { label: 'Downtempo', value: 'downtempo' },
    { label: 'Dream Pop', value: 'dream pop' },
    { label: 'Drill', value: 'drill' },
    { label: 'Drum and Bass', value: 'drum and bass' },
    { label: 'Dub', value: 'dub' },
    { label: 'Dubstep', value: 'dubstep' },
    { label: 'East Coast Hip Hop', value: 'east coast hip hop' },
    { label: 'EDM', value: 'edm' },
    { label: 'Electronic', value: 'electronic' },
    { label: 'Electropop', value: 'electropop' },
    { label: 'Emo', value: 'emo' },
    { label: 'Experimental', value: 'experimental' },
    { label: 'Experimental Rock', value: 'experimental rock' },
    { label: 'Folk', value: 'folk' },
    { label: 'Folk Rock', value: 'folk rock' },
    { label: 'Funk', value: 'funk' },
    { label: 'Garage Rock', value: 'garage rock' },
    { label: 'Gospel', value: 'gospel' },
    { label: 'Grunge', value: 'grunge' },
    { label: 'Hard Bop', value: 'hard bop' },
    { label: 'Hard Rock', value: 'hard rock' },
    { label: 'Hardcore', value: 'hardcore' },
    { label: 'Hardcore Punk', value: 'hardcore punk' },
    { label: 'Heavy Metal', value: 'heavy metal' },
    { label: 'Hip Hop', value: 'hip hop' },
    { label: 'House', value: 'house' },
    { label: 'Indie Pop', value: 'indie pop' },
    { label: 'Indie Rock', value: 'indie rock' },
    { label: 'Industrial', value: 'industrial' },
    { label: 'Industrial Metal', value: 'industrial metal' },
    { label: 'Instrumental', value: 'instrumental' },
    { label: 'Jazz', value: 'jazz' },
    { label: 'Jazz Fusion', value: 'jazz fusion' },
    { label: 'J-Pop', value: 'j-pop' },
    { label: 'K-Pop', value: 'k-pop' },
    { label: 'Latin', value: 'latin' },
    { label: 'Latin Jazz', value: 'latin jazz' },
    { label: 'Lo-Fi', value: 'lo-fi' },
    { label: 'Math Rock', value: 'math rock' },
    { label: 'Melodic Death Metal', value: 'melodic death metal' },
    { label: 'Metal', value: 'metal' },
    { label: 'Metalcore', value: 'metalcore' },
    { label: 'Minimal Techno', value: 'minimal techno' },
    { label: 'Modal Jazz', value: 'modal jazz' },
    { label: 'Neo Soul', value: 'neo soul' },
    { label: 'New Age', value: 'new age' },
    { label: 'New Wave', value: 'new wave' },
    { label: 'Noise Rock', value: 'noise rock' },
    { label: 'Nu Metal', value: 'nu metal' },
    { label: 'Pop', value: 'pop' },
    { label: 'Pop Punk', value: 'pop punk' },
    { label: 'Pop Rock', value: 'pop rock' },
    { label: 'Post-Hardcore', value: 'post-hardcore' },
    { label: 'Post-Punk', value: 'post-punk' },
    { label: 'Post-Rock', value: 'post-rock' },
    { label: 'Power Metal', value: 'power metal' },
    { label: 'Progressive Metal', value: 'progressive metal' },
    { label: 'Progressive Rock', value: 'progressive rock' },
    { label: 'Psychedelic Rock', value: 'psychedelic rock' },
    { label: 'Punk', value: 'punk' },
    { label: 'Punk Rock', value: 'punk rock' },
    { label: 'R&B', value: 'r&b' },
    { label: 'Rap', value: 'rap' },
    { label: 'Reggae', value: 'reggae' },
    { label: 'Reggaeton', value: 'reggaeton' },
    { label: 'Rock', value: 'rock' },
    { label: 'Shoegaze', value: 'shoegaze' },
    { label: 'Singer-Songwriter', value: 'singer-songwriter' },
    { label: 'Ska', value: 'ska' },
    { label: 'Sludge Metal', value: 'sludge metal' },
    { label: 'Soul', value: 'soul' },
    { label: 'Synthpop', value: 'synthpop' },
    { label: 'Techno', value: 'techno' },
    { label: 'Thrash Metal', value: 'thrash metal' },
    { label: 'Trance', value: 'trance' },
    { label: 'Trip Hop', value: 'trip hop' },
]